#ifndef AEGIS_FILE_MINIFILTER_PROTOCOL_H
#define AEGIS_FILE_MINIFILTER_PROTOCOL_H

#include <fltKernel.h>

#define AEGIS_FILE_MINIFILTER_PROTOCOL_VERSION 0x00010000UL

#define AEGIS_FILE_MINIFILTER_SERVICE_NAME_W L"AegisFileMonitor"
#define AEGIS_FILE_MINIFILTER_SERVICE_NAME_A "AegisFileMonitor"
#define AEGIS_FILE_MINIFILTER_PORT_NAME_W L"\\AegisFileMonitorPort"

#define AEGIS_FILE_MINIFILTER_QUEUE_CAPACITY 2048UL
#define AEGIS_FILE_MAX_OPERATION_CHARS 16UL
#define AEGIS_FILE_MAX_PATH_CHARS 512UL
#define AEGIS_FILE_PROTECTED_PATH_CAPACITY 32UL
#define AEGIS_FILE_BLOCK_ENTRY_CAPACITY 64UL

#define AEGIS_FILE_COMMAND_QUERY_STATUS 1UL
#define AEGIS_FILE_COMMAND_QUERY_EVENTS 2UL
#define AEGIS_FILE_COMMAND_PROTECT_PATH 3UL
#define AEGIS_FILE_COMMAND_CLEAR_PROTECTED_PATHS 4UL
#define AEGIS_FILE_COMMAND_QUERY_BLOCK_STATE 5UL
#define AEGIS_FILE_COMMAND_SET_BLOCK_ENTRY 6UL
#define AEGIS_FILE_COMMAND_CLEAR_BLOCK_ENTRIES 7UL

#define AEGIS_FILE_BLOCK_KIND_HASH 1UL
#define AEGIS_FILE_BLOCK_KIND_PID 2UL
#define AEGIS_FILE_BLOCK_KIND_PATH 3UL

#pragma pack(push, 1)

typedef struct _AEGIS_FILE_QUERY_REQUEST {
    ULONG ProtocolVersion;
    ULONG Command;
    ULONG LastSequence;
    ULONG MaxEntries;
} AEGIS_FILE_QUERY_REQUEST, *PAEGIS_FILE_QUERY_REQUEST;

typedef struct _AEGIS_FILE_QUERY_RESPONSE {
    ULONG ProtocolVersion;
    ULONG QueueCapacity;
    ULONG OldestSequence;
    ULONG CurrentSequence;
    ULONG ReturnedCount;
    ULONG Overflowed;
    ULONG ProtectedPathCount;
    ULONG BlockEntryCount;
    ULONG HashBlockCount;
    ULONG PidBlockCount;
    ULONG PathBlockCount;
} AEGIS_FILE_QUERY_RESPONSE, *PAEGIS_FILE_QUERY_RESPONSE;

typedef struct _AEGIS_FILE_PROTECTION_REQUEST {
    ULONG ProtocolVersion;
    ULONG Command;
    WCHAR Path[AEGIS_FILE_MAX_PATH_CHARS];
} AEGIS_FILE_PROTECTION_REQUEST, *PAEGIS_FILE_PROTECTION_REQUEST;

typedef struct _AEGIS_FILE_PROTECTION_RESPONSE {
    ULONG ProtocolVersion;
    ULONG ProtectedPathCount;
} AEGIS_FILE_PROTECTION_RESPONSE, *PAEGIS_FILE_PROTECTION_RESPONSE;

typedef struct _AEGIS_FILE_BLOCK_REQUEST {
    ULONG ProtocolVersion;
    ULONG Command;
    ULONG BlockKind;
    ULONG TtlSeconds;
    ULONG ProcessId;
    WCHAR Target[AEGIS_FILE_MAX_PATH_CHARS];
} AEGIS_FILE_BLOCK_REQUEST, *PAEGIS_FILE_BLOCK_REQUEST;

typedef struct _AEGIS_FILE_BLOCK_RESPONSE {
    ULONG ProtocolVersion;
    ULONG BlockEntryCount;
    ULONG HashBlockCount;
    ULONG PidBlockCount;
    ULONG PathBlockCount;
} AEGIS_FILE_BLOCK_RESPONSE, *PAEGIS_FILE_BLOCK_RESPONSE;

typedef struct _AEGIS_FILE_BLOCK_ENTRY_RECORD {
    ULONG BlockKind;
    ULONG ProcessId;
    ULONG TtlSecondsRemaining;
    WCHAR Target[AEGIS_FILE_MAX_PATH_CHARS];
} AEGIS_FILE_BLOCK_ENTRY_RECORD, *PAEGIS_FILE_BLOCK_ENTRY_RECORD;

typedef struct _AEGIS_FILE_EVENT_RECORD {
    ULONG Sequence;
    LARGE_INTEGER Timestamp;
    ULONG ProcessId;
    WCHAR Operation[AEGIS_FILE_MAX_OPERATION_CHARS];
    WCHAR Path[AEGIS_FILE_MAX_PATH_CHARS];
} AEGIS_FILE_EVENT_RECORD, *PAEGIS_FILE_EVENT_RECORD;

#pragma pack(pop)

#endif
