#ifndef AEGIS_FILE_MINIFILTER_PROTOCOL_H
#define AEGIS_FILE_MINIFILTER_PROTOCOL_H

#include <fltKernel.h>

#define AEGIS_FILE_MINIFILTER_PROTOCOL_VERSION 0x00010000UL

#define AEGIS_FILE_MINIFILTER_SERVICE_NAME_W L"AegisFileMonitor"
#define AEGIS_FILE_MINIFILTER_SERVICE_NAME_A "AegisFileMonitor"
#define AEGIS_FILE_MINIFILTER_PORT_NAME_W L"\\AegisFileMonitorPort"

#define AEGIS_FILE_MINIFILTER_QUEUE_CAPACITY 256UL
#define AEGIS_FILE_MAX_OPERATION_CHARS 16UL
#define AEGIS_FILE_MAX_PATH_CHARS 512UL

#define AEGIS_FILE_COMMAND_QUERY_STATUS 1UL
#define AEGIS_FILE_COMMAND_QUERY_EVENTS 2UL

#pragma pack(push, 1)

typedef struct _AEGIS_FILE_QUERY_REQUEST {
    ULONG ProtocolVersion;
    ULONG Command;
    ULONG LastSequence;
    ULONG MaxEntries;
} AEGIS_FILE_QUERY_REQUEST, *PAEGIS_FILE_QUERY_REQUEST;

typedef struct _AEGIS_FILE_QUERY_RESPONSE {
    ULONG ProtocolVersion;
    ULONG QueueCapacity;
    ULONG OldestSequence;
    ULONG CurrentSequence;
    ULONG ReturnedCount;
    ULONG Overflowed;
} AEGIS_FILE_QUERY_RESPONSE, *PAEGIS_FILE_QUERY_RESPONSE;

typedef struct _AEGIS_FILE_EVENT_RECORD {
    ULONG Sequence;
    LARGE_INTEGER Timestamp;
    ULONG ProcessId;
    WCHAR Operation[AEGIS_FILE_MAX_OPERATION_CHARS];
    WCHAR Path[AEGIS_FILE_MAX_PATH_CHARS];
} AEGIS_FILE_EVENT_RECORD, *PAEGIS_FILE_EVENT_RECORD;

#pragma pack(pop)

#endif
