#ifndef AEGIS_WINDOWS_DRIVER_PROTOCOL_H
#define AEGIS_WINDOWS_DRIVER_PROTOCOL_H

#include <ntddk.h>

#define AEGIS_DRIVER_PROTOCOL_VERSION 0x00010000UL

#define AEGIS_DRIVER_SERVICE_NAME_A "AegisSensorKmod"
#define AEGIS_DRIVER_SERVICE_NAME_W L"AegisSensorKmod"

#define AEGIS_DRIVER_NT_DEVICE_NAME_W L"\\Device\\AegisSensor"
#define AEGIS_DRIVER_DOS_DEVICE_NAME_W L"\\DosDevices\\AegisSensor"
#define AEGIS_DRIVER_DOS_DEVICE_PATH_A "\\\\.\\AegisSensor"

#define AEGIS_DRIVER_VERSION_STRING_A "1.0.0"
#define AEGIS_DRIVER_QUERY_VERSION_JSON \
    "{\"protocol_version\":65536,\"driver_version\":\"1.0.0\"}"

#define AEGIS_IOCTL_QUERY_VERSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_QUERY_STATUS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_QUERY_REGISTRY_EVENTS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_ROLLBACK_REGISTRY_KEY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define AEGIS_DRIVER_REGISTRY_ALTITUDE_W L"385231"

#define AEGIS_REGISTRY_JOURNAL_CAPACITY 256UL
#define AEGIS_REGISTRY_MAX_KEY_PATH_CHARS 512UL
#define AEGIS_REGISTRY_MAX_VALUE_NAME_CHARS 128UL
#define AEGIS_REGISTRY_MAX_VALUE_DATA_BYTES 1024UL

#define AEGIS_REGISTRY_OPERATION_SET 1UL
#define AEGIS_REGISTRY_OPERATION_DELETE 2UL

#pragma pack(push, 1)

typedef struct _AEGIS_DRIVER_STATUS_RESPONSE {
    ULONG ProtocolVersion;
    ULONG RegistryCallbackRegistered;
    ULONG JournalCapacity;
    ULONG JournalCount;
    ULONG OldestSequence;
    ULONG CurrentSequence;
} AEGIS_DRIVER_STATUS_RESPONSE, *PAEGIS_DRIVER_STATUS_RESPONSE;

typedef struct _AEGIS_REGISTRY_EVENT_QUERY_REQUEST {
    ULONG ProtocolVersion;
    ULONG LastSequence;
    ULONG MaxEntries;
} AEGIS_REGISTRY_EVENT_QUERY_REQUEST, *PAEGIS_REGISTRY_EVENT_QUERY_REQUEST;

typedef struct _AEGIS_REGISTRY_EVENT_QUERY_RESPONSE {
    ULONG ProtocolVersion;
    ULONG OldestSequence;
    ULONG CurrentSequence;
    ULONG ReturnedCount;
    ULONG Overflowed;
} AEGIS_REGISTRY_EVENT_QUERY_RESPONSE, *PAEGIS_REGISTRY_EVENT_QUERY_RESPONSE;

typedef struct _AEGIS_REGISTRY_EVENT_RECORD {
    ULONG Sequence;
    LARGE_INTEGER Timestamp;
    ULONG Operation;
    ULONG ValueType;
    ULONG OldDataSize;
    ULONG NewDataSize;
    ULONG OldValuePresent;
    ULONG NewValuePresent;
    ULONG OldDataTruncated;
    ULONG NewDataTruncated;
    WCHAR KeyPath[AEGIS_REGISTRY_MAX_KEY_PATH_CHARS];
    WCHAR ValueName[AEGIS_REGISTRY_MAX_VALUE_NAME_CHARS];
    UCHAR OldData[AEGIS_REGISTRY_MAX_VALUE_DATA_BYTES];
    UCHAR NewData[AEGIS_REGISTRY_MAX_VALUE_DATA_BYTES];
} AEGIS_REGISTRY_EVENT_RECORD, *PAEGIS_REGISTRY_EVENT_RECORD;

typedef struct _AEGIS_REGISTRY_ROLLBACK_REQUEST {
    ULONG ProtocolVersion;
    WCHAR KeyPath[AEGIS_REGISTRY_MAX_KEY_PATH_CHARS];
} AEGIS_REGISTRY_ROLLBACK_REQUEST, *PAEGIS_REGISTRY_ROLLBACK_REQUEST;

typedef struct _AEGIS_REGISTRY_ROLLBACK_RESPONSE {
    ULONG ProtocolVersion;
    ULONG AppliedCount;
    ULONG CurrentSequence;
} AEGIS_REGISTRY_ROLLBACK_RESPONSE, *PAEGIS_REGISTRY_ROLLBACK_RESPONSE;

#pragma pack(pop)

#endif
