#ifndef AEGIS_WINDOWS_DRIVER_PROTOCOL_H
#define AEGIS_WINDOWS_DRIVER_PROTOCOL_H

#include <ntddk.h>

#define AEGIS_DRIVER_PROTOCOL_VERSION 0x00010000UL

#define AEGIS_DRIVER_SERVICE_NAME_A "AegisSensorKmod"
#define AEGIS_DRIVER_SERVICE_NAME_W L"AegisSensorKmod"

#define AEGIS_DRIVER_NT_DEVICE_NAME_W L"\\Device\\AegisSensor"
#define AEGIS_DRIVER_DOS_DEVICE_NAME_W L"\\DosDevices\\AegisSensor"
#define AEGIS_DRIVER_DOS_DEVICE_PATH_A "\\\\.\\AegisSensor"

#define AEGIS_DRIVER_VERSION_STRING_A "1.0.0"
#define AEGIS_DRIVER_QUERY_VERSION_JSON \
    "{\"protocol_version\":65536,\"driver_version\":\"1.0.0\"}"

#define AEGIS_IOCTL_QUERY_VERSION \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_QUERY_STATUS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_QUERY_REGISTRY_EVENTS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_ROLLBACK_REGISTRY_KEY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_PROTECT_PROCESS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_QUERY_INTEGRITY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_PROTECT_REGISTRY_PATH \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define AEGIS_IOCTL_CLEAR_PROTECTED_REGISTRY_PATHS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define AEGIS_DRIVER_REGISTRY_ALTITUDE_W L"385231"
#define AEGIS_DRIVER_PROCESS_PROTECTION_ALTITUDE_W L"385232"

#define AEGIS_REGISTRY_JOURNAL_CAPACITY 256UL
#define AEGIS_REGISTRY_MAX_KEY_PATH_CHARS 512UL
#define AEGIS_REGISTRY_MAX_VALUE_NAME_CHARS 128UL
#define AEGIS_REGISTRY_MAX_VALUE_DATA_BYTES 1024UL
#define AEGIS_REGISTRY_PROTECTED_PATH_CAPACITY 64UL
#define AEGIS_PROCESS_PROTECTION_CAPACITY 64UL

#define AEGIS_INTEGRITY_ROUTINE_COUNT 4UL
#define AEGIS_INTEGRITY_CODEINTEGRITY_OPTION_ENABLED 0x00000001UL
#define AEGIS_INTEGRITY_CODEINTEGRITY_OPTION_TESTSIGN 0x00000002UL
#define AEGIS_INTEGRITY_CODEINTEGRITY_OPTION_UMCI_ENABLED 0x00000004UL
#define AEGIS_INTEGRITY_CODEINTEGRITY_OPTION_HVCI_KMCI_ENABLED 0x00000400UL

#define AEGIS_REGISTRY_OPERATION_SET_VALUE 1UL
#define AEGIS_REGISTRY_OPERATION_DELETE_VALUE 2UL
#define AEGIS_REGISTRY_OPERATION_CREATE_KEY 3UL
#define AEGIS_REGISTRY_OPERATION_DELETE_KEY 4UL

#pragma pack(push, 1)

typedef struct _AEGIS_DRIVER_STATUS_RESPONSE {
    ULONG ProtocolVersion;
    ULONG RegistryCallbackRegistered;
    ULONG JournalCapacity;
    ULONG JournalCount;
    ULONG OldestSequence;
    ULONG CurrentSequence;
    ULONG ObCallbackRegistered;
    ULONG ProtectedProcessCount;
    ULONG ProtectedRegistryPathCount;
} AEGIS_DRIVER_STATUS_RESPONSE, *PAEGIS_DRIVER_STATUS_RESPONSE;

typedef struct _AEGIS_REGISTRY_EVENT_QUERY_REQUEST {
    ULONG ProtocolVersion;
    ULONG LastSequence;
    ULONG MaxEntries;
} AEGIS_REGISTRY_EVENT_QUERY_REQUEST, *PAEGIS_REGISTRY_EVENT_QUERY_REQUEST;

typedef struct _AEGIS_REGISTRY_EVENT_QUERY_RESPONSE {
    ULONG ProtocolVersion;
    ULONG OldestSequence;
    ULONG CurrentSequence;
    ULONG ReturnedCount;
    ULONG Overflowed;
} AEGIS_REGISTRY_EVENT_QUERY_RESPONSE, *PAEGIS_REGISTRY_EVENT_QUERY_RESPONSE;

typedef struct _AEGIS_REGISTRY_EVENT_RECORD {
    ULONG Sequence;
    LARGE_INTEGER Timestamp;
    ULONG Operation;
    ULONG ValueType;
    ULONG OldDataSize;
    ULONG NewDataSize;
    ULONG OldValuePresent;
    ULONG NewValuePresent;
    ULONG OldDataTruncated;
    ULONG NewDataTruncated;
    ULONG Blocked;
    WCHAR KeyPath[AEGIS_REGISTRY_MAX_KEY_PATH_CHARS];
    WCHAR ValueName[AEGIS_REGISTRY_MAX_VALUE_NAME_CHARS];
    UCHAR OldData[AEGIS_REGISTRY_MAX_VALUE_DATA_BYTES];
    UCHAR NewData[AEGIS_REGISTRY_MAX_VALUE_DATA_BYTES];
} AEGIS_REGISTRY_EVENT_RECORD, *PAEGIS_REGISTRY_EVENT_RECORD;

typedef struct _AEGIS_REGISTRY_ROLLBACK_REQUEST {
    ULONG ProtocolVersion;
    WCHAR KeyPath[AEGIS_REGISTRY_MAX_KEY_PATH_CHARS];
} AEGIS_REGISTRY_ROLLBACK_REQUEST, *PAEGIS_REGISTRY_ROLLBACK_REQUEST;

typedef struct _AEGIS_REGISTRY_ROLLBACK_RESPONSE {
    ULONG ProtocolVersion;
    ULONG AppliedCount;
    ULONG CurrentSequence;
} AEGIS_REGISTRY_ROLLBACK_RESPONSE, *PAEGIS_REGISTRY_ROLLBACK_RESPONSE;

typedef struct _AEGIS_PROCESS_PROTECT_REQUEST {
    ULONG ProtocolVersion;
    ULONG ProcessId;
} AEGIS_PROCESS_PROTECT_REQUEST, *PAEGIS_PROCESS_PROTECT_REQUEST;

typedef struct _AEGIS_PROCESS_PROTECT_RESPONSE {
    ULONG ProtocolVersion;
    ULONG ObCallbackRegistered;
    ULONG ProtectedProcessCount;
} AEGIS_PROCESS_PROTECT_RESPONSE, *PAEGIS_PROCESS_PROTECT_RESPONSE;

typedef struct _AEGIS_REGISTRY_PROTECT_REQUEST {
    ULONG ProtocolVersion;
    WCHAR KeyPath[AEGIS_REGISTRY_MAX_KEY_PATH_CHARS];
} AEGIS_REGISTRY_PROTECT_REQUEST, *PAEGIS_REGISTRY_PROTECT_REQUEST;

typedef struct _AEGIS_REGISTRY_PROTECT_RESPONSE {
    ULONG ProtocolVersion;
    ULONG ProtectedPathCount;
} AEGIS_REGISTRY_PROTECT_RESPONSE, *PAEGIS_REGISTRY_PROTECT_RESPONSE;

typedef struct _AEGIS_DRIVER_INTEGRITY_RESPONSE {
    ULONG ProtocolVersion;
    ULONG ObCallbackRegistered;
    ULONG ProtectedProcessCount;
    ULONG SsdtInspectionSucceeded;
    ULONG SsdtSuspicious;
    ULONG CallbackInspectionSucceeded;
    ULONG CallbackSuspicious;
    ULONG KernelCodeInspectionSucceeded;
    ULONG KernelCodeSuspicious;
    ULONG CodeIntegrityOptions;
} AEGIS_DRIVER_INTEGRITY_RESPONSE, *PAEGIS_DRIVER_INTEGRITY_RESPONSE;

#pragma pack(pop)

#endif
